### ISSUE TITLE
Asteroid Ship Collision

### ISSUE THREAD

**Issue by bianca-sparxs** [hicsail/hicsail.github.io#11]
I don't know if this has already been noticed or not lol; 

To calculate the ship asteroid collision, the original squares/triangles are surrounded in a circle that approximates the area of them; now that the triangles are now right triangles, the bounds are completely off and the ship looks like it's exploding in a random place.

In asteroids.js you can see this by setting the SHOW_BOUNDS var to true; 

Also dropping a pic-- the ship will explode and break an asteroid when it hits the pink circles.

![image](https://user-images.githubusercontent.com/33003148/91218472-b6aada80-e6de-11ea-8f3e-39ca7d3b6592.png)

**Comment by frederickjansen** [comment]
Hi Chinwe, thanks for the heads up! One of our interns over the summer did notice this, so it's on our todo list to fix.
